services:
  adguard:
    image: docker.io/adguard/adguardhome:latest
    container_name: adguard
    hostname: adguard
    restart: unless-stopped
    volumes:
      - ./adguard_work:/opt/adguardhome/work
      - ./adguard_conf:/opt/adguardhome/conf
    # Better to disabled mode host, keep using port 3000 to have Caddy use ports 80, 81 and 443
    # network_mode: host
    ports: # host:container
      # DNS
      - "53:53/tcp"
      - "53:53/udp"
      # DHCP
      - "67:67/udp"
      - "68:68/udp"
      # HTTP/HTTPS
      - "3000:80/tcp"
      # - "8443:443/tcp"
      # - "8443:443/udp"
      # - "3000:3000/tcp"
      # DNS over TLS
      - "853:853/tcp"
      # DNS over QUIC
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      # DNS over HTTPS
      - "5443:5443/tcp"
      - "5443:5443/udp"
